const programData = [
  {
    programName: "Program 1",
    programDescription: "Description for Program 1",
    programPreacher: "Preacher A",
    programCoordinator: "Coordinator X",
    programMentor: "Mentor I",
    programIncharge: "Incharge 1",
    programType: "Type X",
    audienceType: "Audience A",
    programLocation: "Location 1",
  },
  {
    programName: "Program 2",
    programDescription: "Description for Program 2",
    programPreacher: "Preacher B",
    programCoordinator: "Coordinator Y",
    programMentor: "Mentor II",
    programIncharge: "Incharge 2",
    programType: "Type Y",
    audienceType: "Audience B",
    programLocation: "Location 2",
  },
  {
    programName: "Program 3",
    programDescription: "Description for Program 3",
    programPreacher: "Preacher C",
    programCoordinator: "Coordinator Z",
    programMentor: "Mentor III",
    programIncharge: "Incharge 3",
    programType: "Type Z",
    audienceType: "Audience C",
    programLocation: "Location 3",
  },
  {
    programName: "Program 4",
    programDescription: "Description for Program 4",
    programPreacher: "Preacher D",
    programCoordinator: "Coordinator A",
    programMentor: "Mentor IV",
    programIncharge: "Incharge 4",
    programType: "Type A",
    audienceType: "Audience D",
    programLocation: "Location 4",
  },
  {
    programName: "Program 5",
    programDescription: "Description for Program 5",
    programPreacher: "Preacher E",
    programCoordinator: "Coordinator B",
    programMentor: "Mentor V",
    programIncharge: "Incharge 5",
    programType: "Type B",
    audienceType: "Audience E",
    programLocation: "Location 5",
  },
  {
    programName: "Program 6",
    programDescription: "Description for Program 6",
    programPreacher: "Preacher F",
    programCoordinator: "Coordinator C",
    programMentor: "Mentor VI",
    programIncharge: "Incharge 6",
    programType: "Type C",
    audienceType: "Audience F",
    programLocation: "Location 6",
  },
  {
    programName: "Program 7",
    programDescription: "Description for Program 7",
    programPreacher: "Preacher G",
    programCoordinator: "Coordinator X",
    programMentor: "Mentor VII",
    programIncharge: "Incharge 7",
    programType: "Type X",
    audienceType: "Audience G",
    programLocation: "Location 7",
  },
  {
    programName: "Program 8",
    programDescription: "Description for Program 8",
    programPreacher: "Preacher H",
    programCoordinator: "Coordinator Y",
    programMentor: "Mentor VIII",
    programIncharge: "Incharge 8",
    programType: "Type Y",
    audienceType: "Audience H",
    programLocation: "Location 8",
  },
  {
    programName: "Program 9",
    programDescription: "Description for Program 9",
    programPreacher: "Preacher I",
    programCoordinator: "Coordinator Z",
    programMentor: "Mentor IX",
    programIncharge: "Incharge 9",
    programType: "Type Z",
    audienceType: "Audience I",
    programLocation: "Location 9",
  },
  {
    programName: "Program 10",
    programDescription: "Description for Program 10",
    programPreacher: "Preacher J",
    programCoordinator: "Coordinator A",
    programMentor: "Mentor X",
    programIncharge: "Incharge 10",
    programType: "Type A",
    audienceType: "Audience J",
    programLocation: "Location 10",
  },
];

export default programData;
