export const courseLevelData = [
  {
    programName: "Introduction to Programming",
    courseLevel: "Beginner",
    preacher: "John Doe",
    mentor: "Jane Smith",
    coordinator: "Alice Johnson",
    status: "Active",
    attendanceUrl: "https://example.com/attendance/intro-programming",
    sessions: [
      { id: "1", sessionName: "Session 1", scheduledDate: "2024-03-02" },
      { id: "2", sessionName: "Session 2", scheduledDate: "2024-03-09" },
      { id: "3", sessionName: "Session 3", scheduledDate: "2024-03-16" },
      { id: "4", sessionName: "Session 4", scheduledDate: "2024-03-23" },
    ],
  },
  {
    programName: "Web Development Basics",
    courseLevel: "Intermediate",
    preacher: "Jane Doe",
    mentor: "Bob Johnson",
    coordinator: "Charlie Brown",
    status: "Active",
    attendanceUrl: "https://example.com/attendance/web-development-basics",
    sessions: [
      { id: "1", sessionName: "Session 1", scheduledDate: "2024-03-02" },
      { id: "2", sessionName: "Session 2", scheduledDate: "2024-03-09" },
      { id: "3", sessionName: "Session 3", scheduledDate: "2024-03-16" },
      { id: "4", sessionName: "Session 4", scheduledDate: "2024-03-23" },
    ],
  },
  {
    programName: "Data Structures and Algorithms",
    courseLevel: "Advanced",
    preacher: "Alice Walker",
    mentor: "Charlie Smith",
    coordinator: "David Johnson",
    status: "Active",
    attendanceUrl: "https://example.com/attendance/data-structures-algorithms",
    sessions: [
      { id: "1", sessionName: "Session 1", scheduledDate: "2024-03-02" },
      { id: "2", sessionName: "Session 2", scheduledDate: "2024-03-09" },
      { id: "3", sessionName: "Session 3", scheduledDate: "2024-03-16" },
      { id: "4", sessionName: "Session 4", scheduledDate: "2024-03-23" },
    ],
  },
  {
    programName: "Mobile App Development",
    courseLevel: "Intermediate",
    preacher: "Bob Doe",
    mentor: "Alice Brown",
    coordinator: "Eve Johnson",
    status: "Inactive",
    attendanceUrl: "https://example.com/attendance/mobile-app-development",
    sessions: [
      { id: "1", sessionName: "Session 1", scheduledDate: "2024-03-02" },
      { id: "2", sessionName: "Session 2", scheduledDate: "2024-03-09" },
      { id: "3", sessionName: "Session 3", scheduledDate: "2024-03-16" },
      { id: "4", sessionName: "Session 4", scheduledDate: "2024-03-23" },
    ],
  },
  {
    programName: "Machine Learning Fundamentals",
    courseLevel: "Advanced",
    preacher: "Eve Doe",
    mentor: "David Brown",
    coordinator: "Frank Johnson",
    status: "Active",
    attendanceUrl:
      "https://example.com/attendance/machine-learning-fundamentals",
    sessions: [
      { id: "1", sessionName: "Session 1", scheduledDate: "2024-03-02" },
      { id: "2", sessionName: "Session 2", scheduledDate: "2024-03-09" },
      { id: "3", sessionName: "Session 3", scheduledDate: "2024-03-16" },
      { id: "4", sessionName: "Session 4", scheduledDate: "2024-03-23" },
    ],
  },
  {
    programName: "Cybersecurity Basics",
    courseLevel: "Intermediate",
    preacher: "Frank Doe",
    mentor: "Eve Smith",
    coordinator: "Grace Johnson",
    status: "Active",
    attendanceUrl: "https://example.com/attendance/cybersecurity-basics",
    sessions: [
      { id: "1", sessionName: "Session 1", scheduledDate: "2024-03-02" },
      { id: "2", sessionName: "Session 2", scheduledDate: "2024-03-09" },
      { id: "3", sessionName: "Session 3", scheduledDate: "2024-03-16" },
      { id: "4", sessionName: "Session 4", scheduledDate: "2024-03-23" },
    ],
  },
  {
    programName: "Data Analytics",
    courseLevel: "Intermediate",
    preacher: "Grace Doe",
    mentor: "Frank Smith",
    coordinator: "Henry Johnson",
    status: "Inactive",
    attendanceUrl: "https://example.com/attendance/data-analytics",
    sessions: [
      { id: "1", sessionName: "Session 1", scheduledDate: "2024-03-02" },
      { id: "2", sessionName: "Session 2", scheduledDate: "2024-03-09" },
      { id: "3", sessionName: "Session 3", scheduledDate: "2024-03-16" },
      { id: "4", sessionName: "Session 4", scheduledDate: "2024-03-23" },
    ],
  },
  {
    programName: "Frontend Web Development",
    courseLevel: "Intermediate",
    preacher: "Henry Doe",
    mentor: "Grace Smith",
    coordinator: "Ivy Johnson",
    status: "Active",
    attendanceUrl: "https://example.com/attendance/frontend-web-development",
    sessions: [
      { id: "1", sessionName: "Session 1", scheduledDate: "2024-03-02" },
      { id: "2", sessionName: "Session 2", scheduledDate: "2024-03-09" },
      { id: "3", sessionName: "Session 3", scheduledDate: "2024-03-16" },
      { id: "4", sessionName: "Session 4", scheduledDate: "2024-03-23" },
    ],
  },
  {
    programName: "Backend Web Development",
    courseLevel: "Intermediate",
    preacher: "Ivy Doe",
    mentor: "Henry Smith",
    coordinator: "Jack Johnson",
    status: "Active",
    attendanceUrl: "https://example.com/attendance/backend-web-development",
    sessions: [
      { id: "1", sessionName: "Session 1", scheduledDate: "2024-03-02" },
      { id: "2", sessionName: "Session 2", scheduledDate: "2024-03-09" },
      { id: "3", sessionName: "Session 3", scheduledDate: "2024-03-16" },
      { id: "4", sessionName: "Session 4", scheduledDate: "2024-03-23" },
    ],
  },
  {
    programName: "Artificial Intelligence",
    courseLevel: "Advanced",
    preacher: "Jack Doe",
    mentor: "Ivy Smith",
    coordinator: "John Johnson",
    status: "Active",
    attendanceUrl: "https://example.com/attendance/artificial-intelligence",
    sessions: [
      { id: "1", sessionName: "Session 1", scheduledDate: "2024-03-02" },
      { id: "2", sessionName: "Session 2", scheduledDate: "2024-03-09" },
      { id: "3", sessionName: "Session 3", scheduledDate: "2024-03-16" },
      { id: "4", sessionName: "Session 4", scheduledDate: "2024-03-23" },
    ],
  },
];
