export const activitiesData = [
  {
    programName: "GitaSaar Batch 5",
    courseCode: "DYS",
    sessionName: "DYS 3 - Discover Manual of Life",
    status: "Active",
    typeofActivity: "Attendence",
    Phone: "4574686485",
    FirstName: "John",
    LastName: "John",
    date: "1/21/24",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
  },
  {
    programName: "GitaSaar Batch 5",
    courseCode: "DYS",
    sessionName: "DYS 4 - Discover Lasting Solution",
    status: "Active",
    typeofActivity: "Attendence",
    Phone: "3463634633",
    FirstName: "Anna",
    LastName: "Alice",
    date: "1/22/24",
    startTime: "2:00 PM",
    endTime: "3:00 PM",
  },
  {
    programName: "GitaSaar Batch 5",
    courseCode: "",
    sessionName: "",
    status: "Active",
    typeofActivity: "Chanting 2 round",
    Phone: "5685858588",
    FirstName: "John",
    LastName: "Bob",
    date: "1/23/24",
    startTime: "11:30 AM",
    endTime: "1:00 PM",
  },
  {
    programName: "GitaSaar Batch 9",
    courseCode: "DYS",
    sessionName: "DYS 1 - Discover Inner Self",
    status: "InActive",
    typeofActivity: "Attendence",
    Phone: "3463578899",
    FirstName: "Anne",
    LastName: "Eva",
    date: "1/25/24",
    startTime: "8:00 AM",
    endTime: "9:00 AM",
  },
  {
    programName: "GitaSaar Batch 9",
    courseCode: "DYS",
    sessionName: "DYS 8 - Discover the Essence",
    status: "InActive",
    typeofActivity: "Attendence",
    Phone: "2352626266",
    FirstName: "Jahan",
    LastName: "Chris",
    date: "1/26/24",
    startTime: "3:30 PM",
    endTime: "5:00 PM",
  },
  {
    programName: "Sunday Morning BG",
    courseCode: "DYS",
    sessionName: "DYS 1 - Discover Inner Self",
    status: "Active",
    typeofActivity: "Attendence",
    Phone: "3463463678",
    FirstName: "Jaden",
    LastName: "Linda",
    date: "1/28/24",
    startTime: "6:00 PM",
    endTime: "8:00 PM",
  },
  {
    programName: "Sunday Morning BG",
    courseCode: "BG",
    sessionName: "Chapter 2, Text 8-15",
    status: "Active",
    typeofActivity: "Attendence",
    Phone: "2536778854",
    FirstName: "Smilga",
    LastName: "Mike",
    date: "1/30/24",
    startTime: "7:30 PM",
    endTime: "9:00 PM",
  },
  {
    programName: "CeraTech Society",
    courseCode: "DYS",
    sessionName: "DYS 6 - Discover Real Eternal Love ",
    status: "Active",
    typeofActivity: "Attendence",
    Phone: "3467448788",
    FirstName: "Charlie",
    LastName: "Emily",
    date: "2/1/24",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
  },
  {
    programName: "CeraTech Society",
    courseCode: "BG",
    sessionName: "Chapter 1, Text 8-15",
    status: "Active",
    typeofActivity: "Attendence",
    Phone: "3235638998",
    FirstName: "Tyler",
    LastName: "John",
    date: "2/3/24",
    startTime: "1:00 PM",
    endTime: "2:30 PM",
  },
  {
    programName: "Akruti Society",
    courseCode: "BG",
    sessionName: "Chapter 2, Text 8-15",
    status: "Active",
    typeofActivity: "Attendence",
    Phone: "3465346367",
    FirstName: "Durden",
    LastName: "Sara",
    date: "2/5/24",
    startTime: "9:00 AM",
    endTime: "",
  },
  {
    programName: "GitaSaar Batch 5",
    courseCode: "",
    sessionName: "",
    status: "Active",
    typeofActivity: "Chanting 1 round",
    Phone: "4574686485",
    FirstName: "John",
    LastName: "Sweck",
    date: "1/21/24",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
  },
  {
    programName: "GitaSaar Batch 5",
    courseCode: "",
    sessionName: "",
    status: "Active",
    typeofActivity: "Chanting 2 round",
    Phone: "3463634633",
    FirstName: "John",
    LastName: "Alice",
    date: "1/22/24",
    startTime: "2:00 PM",
    endTime: "3:00 PM",
  },
  {
    programName: "GitaSaar Batch 5",
    courseCode: "Game",
    sessionName: "Spirit of Bhagavad-gita",
    status: "Active",
    typeofActivity: "Visited temple",
    Phone: "5685858588",
    FirstName: "John",
    LastName: "Bob",
    date: "1/23/24",
    startTime: "11:30 AM",
    endTime: "1:00 PM",
  },
  {
    programName: "GitaSaar Batch 9",
    courseCode: "Game",
    sessionName: "Test of a sincere Disciple",
    status: "InActive",
    typeofActivity: "Attendence",
    Phone: "3463578899",
    FirstName: "John",
    LastName: "Eva",
    date: "1/25/24",
    startTime: "8:00 AM",
    endTime: "9:00 AM",
  },
  {
    programName: "GitaSaar Batch 9",
    courseCode: "",
    sessionName: "",
    status: "InActive",
    typeofActivity: "Chanting 4 round",
    Phone: "2352626266",
    FirstName: "John",
    LastName: "Chris",
    date: "1/26/24",
    startTime: "3:30 PM",
    endTime: "5:00 PM",
  },
  {
    programName: "Sunday Morning BG",
    courseCode: "",
    sessionName: "",
    status: "Active",
    typeofActivity: "Chanting 16 round",
    Phone: "3463463678",
    FirstName: "John",
    LastName: "Linda",
    date: "1/28/24",
    startTime: "6:00 PM",
    endTime: "8:00 PM",
  },
  {
    programName: "Sunday Morning BG",
    courseCode: "",
    sessionName: "",
    status: "Active",
    typeofActivity: "Received Completion Certification",
    Phone: "2536778854",
    FirstName: "John",
    LastName: "Mike",
    date: "1/30/24",
    startTime: "7:30 PM",
    endTime: "9:00 PM",
  },
  {
    programName: "CeraTech Society",
    courseCode: "DYS",
    sessionName: "DYS 1 - Discover Inner Self",
    status: "Active",
    typeofActivity: "Registered For Course",
    Phone: "3467448788",
    FirstName: "John",
    LastName: "Emily",
    date: "2/1/24",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
  },
  {
    programName: "CeraTech Society",
    courseCode: "DYS",
    sessionName: "DYS 1 - Discover Inner Self",
    status: "Active",
    typeofActivity: "Registered For Course",
    Phone: "3235638998",
    FirstName: "John",
    LastName: "John",
    date: "2/3/24",
    startTime: "1:00 PM",
    endTime: "2:30 PM",
  },
  {
    programName: "Akruti Society",
    courseCode: "",
    sessionName: "",
    status: "Active",
    typeofActivity: "Visited temple",
    Phone: "3465346367",
    FirstName: "John",
    LastName: "Sara",
    date: "2/5/24",
    startTime: "9:00 AM",
    endTime: "",
  },
];
