export const activitiesData = [
  {
    programName: "GitaSaar Batch 5",
    courseCode: "DYS",
    sessionName: "DYS 3 - Discover Manual of Life",
    status: "Active",
    Activity: "Attendence",
    Phone: 4574686485,
    LastName: "John",
    date: "01/21/2024",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
  },
  {
    programName: "GitaSaar Batch 5",
    courseCode: "DYS",
    sessionName: "DYS 4 - Discover Lasting Solution",
    status: "Active",
    Activity: "Attendence",
    Phone: 3463634633,
    LastName: "Alice",
    date: "01/22/2024",
    startTime: "2:00 PM",
    endTime: "3:00 PM",
  },
  {
    programName: "GitaSaar Batch 5",
    status: "Active",
    Activity: "Chanting 2 round",
    Phone: 5685858588,
    LastName: "Bob",
    date: "01/23/2024",
    startTime: "11:30 AM",
    endTime: "1:00 PM",
  },
  {
    programName: "GitaSaar Batch 9",
    courseCode: "DYS",
    sessionName: "DYS 1 - Discover Inner Self",
    status: "InActive",
    Activity: "Attendence",
    Phone: 3463578899,
    LastName: "Eva",
    date: "01/25/2024",
    startTime: "8:00 AM",
    endTime: "9:00 AM",
  },
  {
    programName: "GitaSaar Batch 9",
    courseCode: "DYS",
    sessionName: "DYS 8 - Discover the Essence",
    status: "InActive",
    Activity: "Attendence",
    Phone: 2352626266,
    LastName: "Chris",
    date: "01/26/2024",
    startTime: "3:30 PM",
    endTime: "5:00 PM",
  },
  {
    programName: "Sunday Morning BG",
    courseCode: "DYS",
    sessionName: "DYS 1 - Discover Inner Self",
    status: "Active",
    Activity: "Attendence",
    Phone: 3463463678,
    LastName: "Linda",
    date: "01/28/2024",
    startTime: "6:00 PM",
    endTime: "8:00 PM",
  },
  {
    programName: "Sunday Morning BG",
    courseCode: "BG",
    sessionName: "Chapter 2, Text 8-15",
    status: "Active",
    Activity: "Attendence",
    Phone: 2536778854,
    LastName: "Mike",
    date: "01/30/2024",
    startTime: "7:30 PM",
    endTime: "9:00 PM",
  },
  {
    programName: "CeraTech Society",
    courseCode: "DYS",
    sessionName: "DYS 6 - Discover Real Eternal Love ",
    status: "Active",
    Activity: "Attendence",
    Phone: 3467448788,
    LastName: "Emily",
    date: "02/01/2024",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
  },
  {
    programName: "CeraTech Society",
    courseCode: "BG",
    sessionName: "Chapter 1, Text 8-15",
    status: "Active",
    Activity: "Attendence",
    Phone: 3235638998,
    LastName: "John",
    date: "02/03/2024",
    startTime: "1:00 PM",
    endTime: "2:30 PM",
  },
  {
    programName: "Akruti Society",
    courseCode: "BG",
    sessionName: "Chapter 2, Text 8-15",
    status: "Active",
    Activity: "Attendence",
    Phone: 3465346367,
    LastName: "Sara",
    date: "02/05/2024",
    startTime: "9:00 AM",
  },
  {
    programName: "GitaSaar Batch 5",
    status: "Active",
    Activity: "Chanting 1 round",
    Phone: 4574686485,
    LastName: "John",
    date: "01/21/2024",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
  },
  {
    programName: "GitaSaar Batch 5",
    status: "Active",
    Activity: "Chanting 2 round",
    Phone: 3463634633,
    LastName: "Alice",
    date: "01/22/2024",
    startTime: "2:00 PM",
    endTime: "3:00 PM",
  },
  {
    programName: "GitaSaar Batch 5",
    courseCode: "Game",
    sessionName: "Spirit of Bhagavad-gita",
    status: "Active",
    Activity: "Visited temple",
    Phone: 5685858588,
    LastName: "Bob",
    date: "01/23/2024",
    startTime: "11:30 AM",
    endTime: "1:00 PM",
  },
  {
    programName: "GitaSaar Batch 9",
    courseCode: "Game",
    sessionName: "Test of a sincere Disciple",
    status: "InActive",
    Activity: "Attendence",
    Phone: 3463578899,
    LastName: "Eva",
    date: "01/25/2024",
    startTime: "8:00 AM",
    endTime: "9:00 AM",
  },
  {
    programName: "GitaSaar Batch 9",
    status: "InActive",
    Activity: "Chanting 4 round",
    Phone: 2352626266,
    LastName: "Chris",
    date: "01/26/2024",
    startTime: "3:30 PM",
    endTime: "5:00 PM",
  },
  {
    programName: "Sunday Morning BG",
    status: "Active",
    Activity: "Chanting 16 round",
    Phone: 3463463678,
    LastName: "Linda",
    date: "01/28/2024",
    startTime: "6:00 PM",
    endTime: "8:00 PM",
  },
  {
    programName: "Sunday Morning BG",
    status: "Active",
    Activity: "Received Completion Certification",
    Phone: 2536778854,
    LastName: "Mike",
    date: "01/30/2024",
    startTime: "7:30 PM",
    endTime: "9:00 PM",
  },
  {
    programName: "CeraTech Society",
    courseCode: "DYS",
    sessionName: "DYS 1 - Discover Inner Self",
    status: "Active",
    Activity: "Registered For Course",
    Phone: 3467448788,
    LastName: "Emily",
    date: "02/01/2024",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
  },
  {
    programName: "CeraTech Society",
    courseCode: "DYS",
    sessionName: "DYS 1 - Discover Inner Self",
    status: "Active",
    Activity: "Registered For Course",
    Phone: 3235638998,
    LastName: "John",
    date: "02/03/2024",
    startTime: "1:00 PM",
    endTime: "2:30 PM",
  },
  {
    programName: "Akruti Society",
    status: "Active",
    Activity: "Visited temple",
    Phone: 3465346367,
    LastName: "Sara",
    date: "02/05/2024",
    startTime: "9:00 AM",
  },
];
