export const activitiesData = [
  {
    FirstName: "John",
    LastName: "Doe",
    programName: "Mindfulness Meditation",
    courseCode: "MED101",
    sessionName: "Introduction to Meditation",
    status: "active",
    typeofActivity: "chanting 1 round",
    date: "2024-01-21",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
  },
  {
    FirstName: "Alice",
    LastName: "Smith",
    programName: "Yoga and Relaxation",
    courseCode: "YOGA202",
    sessionName: "Yoga for Stress Relief",
    status: "inactive",
    typeofActivity: "chanting 2 round",
    date: "2024-01-22",
    startTime: "02:00 PM",
    endTime: "03:00 PM",
  },
  {
    FirstName: "Bob",
    LastName: "Johnson",
    programName: "Cultural Excursion",
    courseCode: "CUL301",
    sessionName: "Visiting Temple",
    status: "active",
    typeofActivity: "visited temple",
    date: "2024-01-23",
    startTime: "11:30 AM",
    endTime: "01:00 PM",
  },
  {
    FirstName: "Eva",
    LastName: "Anderson",
    programName: "Fitness Bootcamp",
    courseCode: "FIT401",
    sessionName: "HIIT Workout",
    status: "active",
    typeofActivity: "workout",
    date: "2024-01-25",
    startTime: "08:00 AM",
    endTime: "09:00 AM",
  },
  {
    FirstName: "Chris",
    LastName: "Williams",
    programName: "Art Workshop",
    courseCode: "ART501",
    sessionName: "Painting Class",
    status: "inactive",
    typeofActivity: "art session",
    date: "2024-01-26",
    startTime: "03:30 PM",
    endTime: "05:00 PM",
  },
  {
    FirstName: "Linda",
    LastName: "Martin",
    programName: "Cooking Class",
    courseCode: "COOK601",
    sessionName: "Italian Cuisine",
    status: "active",
    typeofActivity: "cooking",
    date: "2024-01-28",
    startTime: "06:00 PM",
    endTime: "08:00 PM",
  },
  {
    FirstName: "Mike",
    LastName: "Taylor",
    programName: "Language Exchange",
    courseCode: "LANG701",
    sessionName: "Spanish Conversation",
    status: "active",
    typeofActivity: "language exchange",
    date: "2024-01-30",
    startTime: "07:30 PM",
    endTime: "09:00 PM",
  },
  {
    FirstName: "Emily",
    LastName: "Clark",
    programName: "Photography Workshop",
    courseCode: "PHOTO801",
    sessionName: "Nature Photography",
    status: "inactive",
    typeofActivity: "photography session",
    date: "2024-02-01",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
  },
  {
    FirstName: "John",
    LastName: "Miller",
    programName: "Tech Talk",
    courseCode: "TECH901",
    sessionName: "Introduction to AI",
    status: "active",
    typeofActivity: "tech discussion",
    date: "2024-02-03",
    startTime: "01:00 PM",
    endTime: "02:30 PM",
  },
  {
    FirstName: "Sara",
    LastName: "Baker",
    programName: "Gardening Club",
    courseCode: "GARDEN101",
    sessionName: "Plant Care Tips",
    status: "inactive",
    typeofActivity: "gardening",
    date: "2024-02-05",
    startTime: "09:00 AM",
    endTime: "10:30 AM",
  },
];
